development:
  default:
    from_address: 'info@arkhitech.com'
    url_options:
      host: 'localhost:3000'
  facebook:
    app_key: '1412627235639386'
    secret_token: '5be4a30e3e20081dfa579be9dd96cf91'
  action_mailer_smtp_settings:
    user_name: 'hisham.malik'
    password: 'testing1234'
    domain: 'arkhitech.com'
    address: 'smtp.sendgrid.net'
    port: 587
    authentication: :plain
    enable_starttls_auto: true

production:
  default:
    from_address: 'info@arkhitech.com'
    url_options:
      host: 'localhost:3000'
  facebook:
    app_key: '1412627235639386'
    secret_token: '5be4a30e3e20081dfa579be9dd96cf91'
  action_mailer_smtp_settings:
    user_name: 'hisham.malik'
    password: 'testing1234'
    domain: 'arkhitech.com'
    address: 'smtp.sendgrid.net'
    port: 587
    authentication: :plain
    enable_starttls_auto: true

