development:
  facebook:
    app_key: '522695187818535'
    secret_token: 'ab0df8696fbe5d3c10f00ca303eb5c7d'
  action_mailer_smtp_settings:
    user_name: 'hisham.malik'
    password: 'testing1234'
    domain: 'arkhitech.com'
    address: 'smtp.sendgrid.net'
    port: 587
    authentication: :plain
    enable_starttls_auto: true

production:
  facebook:
    app_key: '522695187818535'
    secret_token: 'ab0df8696fbe5d3c10f00ca303eb5c7d'
  action_mailer_smtp_settings:
    user_name: 'hisham.malik'
    password: 'testing1234'
    domain: 'arkhitech.com'
    address: 'smtp.sendgrid.net'
    port: 587
    authentication: :plain
    enable_starttls_auto: true